"""
Git integration for the AI Factory.

Automatically initializes Git repos in project workspaces and pushes
generated code to GitHub after successful delivery.

Features:
- Auto git init + initial commit after code generation
- Creates GitHub repo via gh CLI or API
- Pushes code after delivery stage
- Stores repo URL in Deployment record

Environment variables:
- GITHUB_TOKEN: Personal access token with 'repo' scope
- GITHUB_ORG: Optional org name (defaults to user's personal account)
- GIT_AUTO_PUSH: Set to "true" to enable auto-push (default: false)
"""
import asyncio
import os
from pathlib import Path
from typing import Optional


class GitManager:
    """Manages Git operations for project workspaces."""

    def __init__(self, workspace_root: str = "./workspace") -> None:
        self.workspace_root = Path(workspace_root)
        self.github_token = os.getenv("GITHUB_TOKEN", "")
        self.github_org = os.getenv("GITHUB_ORG", "")
        self.auto_push = os.getenv("GIT_AUTO_PUSH", "false").lower() == "true"

    async def init_repo(self, project_id: str, project_name: str) -> Optional[str]:
        """
        Initialize a Git repository in the project workspace.

        Args:
            project_id: Project UUID
            project_name: Human-readable project name

        Returns:
            str: Path to the initialized repo, or None on failure
        """
        workspace = self.workspace_root / project_id
        if not workspace.exists():
            return None

        try:
            # Initialize git repo
            await self._run_git(workspace, "init")
            await self._run_git(workspace, "checkout", "-b", "main")

            # Create .gitignore
            gitignore = workspace / ".gitignore"
            if not gitignore.exists():
                gitignore.write_text(
                    "__pycache__/\n*.pyc\n.env\nnode_modules/\n"
                    ".venv/\nvenv/\ndist/\nbuild/\n*.egg-info/\n"
                    ".pytest_cache/\n.coverage\n"
                )

            # Stage all files and commit
            await self._run_git(workspace, "add", "-A")
            await self._run_git(
                workspace, "commit", "-m",
                f"feat: initial code generation by AI Factory\n\n"
                f"Project: {project_name}\n"
                f"Generated by Autonomous AI Software Factory",
            )

            return str(workspace)

        except Exception as e:
            # Git init failure should not block pipeline
            return None

    async def push_to_github(
        self,
        project_id: str,
        project_name: str,
        private: bool = True,
    ) -> Optional[str]:
        """
        Create a GitHub repo and push the project code.

        Args:
            project_id: Project UUID
            project_name: Project name (used for repo name)
            private: Whether the repo should be private

        Returns:
            str: GitHub repo URL, or None on failure
        """
        if not self.github_token:
            return None

        workspace = self.workspace_root / project_id
        if not workspace.exists():
            return None

        # Sanitize repo name
        repo_name = self._sanitize_repo_name(project_name)

        try:
            # Create repo via GitHub API
            repo_url = await self._create_github_repo(repo_name, private=private)
            if not repo_url:
                return None

            # Set remote and push
            await self._run_git(workspace, "remote", "add", "origin", repo_url)
            await self._run_git(
                workspace, "push", "-u", "origin", "main",
                env={"GIT_ASKPASS": "echo", "GIT_TERMINAL_PROMPT": "0"},
            )

            return repo_url

        except Exception:
            return None

    async def commit_changes(
        self,
        project_id: str,
        message: str = "fix: automated code fix by AI Factory",
    ) -> bool:
        """
        Stage and commit any changes in the workspace (e.g., after fixing).

        Args:
            project_id: Project UUID
            message: Commit message

        Returns:
            bool: True if commit was made, False otherwise
        """
        workspace = self.workspace_root / project_id
        if not workspace.exists() or not (workspace / ".git").exists():
            return False

        try:
            # Check if there are changes
            stdout, _, rc = await self._run_git_output(workspace, "status", "--porcelain")
            if not stdout.strip():
                return False  # No changes

            await self._run_git(workspace, "add", "-A")
            await self._run_git(workspace, "commit", "-m", message)

            # Auto-push if enabled and remote exists
            if self.auto_push:
                _, _, rc = await self._run_git_output(workspace, "remote", "get-url", "origin")
                if rc == 0:
                    await self._run_git(
                        workspace, "push", "origin", "main",
                        env={"GIT_ASKPASS": "echo", "GIT_TERMINAL_PROMPT": "0"},
                    )

            return True

        except Exception:
            return False

    async def _create_github_repo(self, name: str, private: bool = True) -> Optional[str]:
        """Create a GitHub repo via the REST API."""
        import json

        url = "https://api.github.com/user/repos"
        if self.github_org:
            url = f"https://api.github.com/orgs/{self.github_org}/repos"

        payload = json.dumps({
            "name": name,
            "private": private,
            "auto_init": False,
            "description": f"Generated by Autonomous AI Software Factory",
        })

        cmd = (
            f'curl -s -X POST "{url}" '
            f'-H "Authorization: token {self.github_token}" '
            f'-H "Content-Type: application/json" '
            f'-d \'{payload}\''
        )

        process = await asyncio.create_subprocess_shell(
            cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, _ = await process.communicate()
        response = stdout.decode("utf-8", errors="replace")

        try:
            data = json.loads(response)
            # Use SSH URL for push (works behind GFW with SSH keys configured)
            return data.get("ssh_url") or data.get("clone_url")
        except (json.JSONDecodeError, KeyError):
            return None

    async def _run_git(self, cwd: Path, *args: str, env: Optional[dict] = None) -> None:
        """Run a git command, raising on failure."""
        full_env = os.environ.copy()
        if env:
            full_env.update(env)
        if self.github_token:
            full_env["GIT_AUTHOR_NAME"] = "AI Factory"
            full_env["GIT_AUTHOR_EMAIL"] = "ai-factory@noreply.local"
            full_env["GIT_COMMITTER_NAME"] = "AI Factory"
            full_env["GIT_COMMITTER_EMAIL"] = "ai-factory@noreply.local"

        process = await asyncio.create_subprocess_exec(
            "git", *args,
            cwd=str(cwd),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=full_env,
        )
        _, stderr = await asyncio.wait_for(process.communicate(), timeout=30)
        if process.returncode != 0:
            raise RuntimeError(f"git {' '.join(args)} failed: {stderr.decode()[:200]}")

    async def _run_git_output(self, cwd: Path, *args: str) -> tuple[str, str, int]:
        """Run a git command and return (stdout, stderr, returncode)."""
        process = await asyncio.create_subprocess_exec(
            "git", *args,
            cwd=str(cwd),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=30)
        return (
            stdout.decode("utf-8", errors="replace"),
            stderr.decode("utf-8", errors="replace"),
            process.returncode or 0,
        )

    @staticmethod
    def _sanitize_repo_name(name: str) -> str:
        """Sanitize a project name into a valid GitHub repo name."""
        import re
        # Replace spaces and special chars with hyphens
        sanitized = re.sub(r"[^a-zA-Z0-9._-]", "-", name.lower())
        # Remove consecutive hyphens
        sanitized = re.sub(r"-+", "-", sanitized).strip("-")
        # Truncate to 100 chars
        return sanitized[:100] or "ai-factory-project"
